### ISSUE TITLE
Fix crashes when clicking setting

### ISSUE THREAD

**Issue by n78** [bubelov/news#143]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to sidebar
2. Press on setting

### Actual behavior

The application crashes

### Expected behavior

Open the setting screen

### Logs

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	... 1 more
Caused by: org.koin.core.error.NoBeanDefFoundException: |- No definition found for class:'settings.SettingsViewModel'. Check your definitions!
	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:305)
	at org.koin.core.scope.Scope.resolveValue(Scope.kt:275)
	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:242)
	at org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:36)
	at org.koin.core.scope.Scope$get$1.invoke(Scope.kt:200)
	at org.koin.core.time.MeasureKt.measureTimedValue(Measure.kt:47)
	at org.koin.core.time.MeasureKt.measureDurationForResult(Measure.kt:41)
	at org.koin.core.scope.Scope.get(Scope.kt:199)
	at org.koin.androidx.viewmodel.factory.DefaultViewModelFactory.create(DefaultViewModelFactory.kt:13)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:171)
	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.kt:139)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:44)
	at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:31)
	at settings.SettingsFragment.getModel(SettingsFragment.kt:33)
	at settings.SettingsFragment.access$getModel(SettingsFragment.kt:31)
	at settings.SettingsFragment$onViewCreated$conf$1.invokeSuspend(SettingsFragment.kt:83)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at settings.SettingsFragment.onViewCreated(SettingsFragment.kt:83)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3019)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1840)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1764)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1701)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:488)
	at android.os.Handler.handleCallback(Handler.java:914)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:227)
	at android.app.ActivityThread.main(ActivityThread.java:7610)
	... 3 more

It's the latest CI build version from GitHub actions.
### Device info

 - Android version/Custom ROM version: Android 10/MIUI 12
 - Device model:MI 6X

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/d40178f0378d3a1b387b669734d4074807f2ce2d

Please note that the preview branch can be super unstable so its better to make OPML backups every time you add or delete a feed in standalone mode
