### ISSUE TITLE
Crashes lately 

### ISSUE THREAD

**Issue by C8opmBM** [bubelov/news#152]
So I've been having constant crashes lately. I don't know what causes them, could be related to latest Android 12 updates maybe since I haven't experienced them before.
I'm on pixel 6, up to date with android 12.

Here is the crash log, maybe you could look into it.
Thanks.

````
type: crash
osVersion: google/oriole/oriole:12/SQ3A.220705.004/2022080900:user/release-keys
package: co.appreactor.news:20
process: co.appreactor.news

java.lang.NullPointerException
	at db.app.EntryQueriesImpl$selectByReadOrBookmarked$1.invoke(DatabaseImpl.kt:1096)
	at db.app.EntryQueriesImpl$selectByReadOrBookmarked$1.invoke(DatabaseImpl.kt:1094)
	at com.squareup.sqldelight.Query.executeAsList(Query.kt:135)
	at com.squareup.sqldelight.runtime.coroutines.FlowQuery$mapToList$1$1.invokeSuspend(FlowExtensions.kt:98)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

````

**Comment by C8opmBM** [comment]
You've committed so much since the latest release in February, I'm thinking to install the latest dev build to see if crashes are still present there.

**Comment by bubelov** [comment]
@C8opmBM yep, you can try that. The new release is expected within a few weeks

**Comment by C8opmBM** [comment]
No more crashes. I had 2 bookmarks which errored out when adding them, so possibly that was the error.
