### ISSUE TITLE
Error after Nextcloud Login

### ISSUE THREAD

**Issue by dontobi** [bubelov/news#156]
### Checklist 
- [x] I am using the latest version
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug
1. Install latest debug apk
2. Open the App
3. Log in to Nextcloud

### Actual behavior
With the debug APK I always get this error after login with Nextcloud.

### Expected behavior
The app should not crash.

### Screenshots/Screen recordings
![Screenshot_20220826-131539.png](https://user-images.githubusercontent.com/19261667/186892011-c9c6a926-d4d5-4f3e-a1d4-ea3fdb2bed35.png)

### Logs
[Download from GDrive](https://drive.google.com/file/d/1OaVQC5r4r0pF-3HJwbFqBls377mW09o8/view?usp=drivesdk)

### Device: 
 - Android Version: Android 13
 - Build: TP1A.220624.021
 - Device model: Google Pixel 6

**Comment by bubelov** [comment]
```
    java.lang.IllegalArgumentException: Navigation action/destination co.appreactor.news.debug:id/action_minifluxAuthFragment_to_newsFragment cannot be found from the current destination Destination(co.appreactor.news.debug:id/nextcloudAuthFragment) label=NextcloudAuthFragment class=auth.NextcloudAuthFragment
        at androidx.navigation.NavController.navigate(NavController.kt:1536)
        at androidx.navigation.NavController.navigate(NavController.kt:1468)
        at androidx.navigation.NavController.navigate(NavController.kt:1450)
        at androidx.navigation.NavController.navigate(NavController.kt:1433)
        at auth.NextcloudAuthFragment$connect$1.invokeSuspend(NextcloudAuthFragment.kt:83)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at androidx.lifecycle.DispatchQueue.drainQueue(DispatchQueue.kt:75)
        at androidx.lifecycle.DispatchQueue.enqueue(DispatchQueue.kt:112)
        at androidx.lifecycle.DispatchQueue.dispatchAndEnqueue$lambda-2$lambda-1(DispatchQueue.kt:100)
        at androidx.lifecycle.DispatchQueue.$r8$lambda$G2ay370n_s_ksSHUJaD9zIU8eCw(Unknown Source:0)
        at androidx.lifecycle.DispatchQueue$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e9549c9, Dispatchers.Main.immediate]
```

**Comment by bubelov** [comment]
Fixed in https://github.com/bubelov/news/commit/498b233f2aa8ee6358e435c65afe19a8be6891a1

**Comment by dontobi** [comment]
Thanks
