### ISSUE TITLE
NullPointerException when importing from OPML file

### ISSUE THREAD

**Issue by Tiger3030** [bubelov/news#55]
When I try to import feeds from an OPML file I get the following exception:

```
java.lang.NullPointerException: getAttributeValue(null, Symbols.TYPE) must not be null
	at opml.OpmlKt.importOpml(Opml.kt:49)
	at feeds.FeedsViewModel$importFeeds$2.invokeSuspend(FeedsViewModel.kt:52)
	at feeds.FeedsViewModel$importFeeds$2.invoke(Unknown Source:10)
	at feeds.FeedsViewModel.changeState(FeedsViewModel.kt:106)
	at feeds.FeedsViewModel.importFeeds(FeedsViewModel.kt:49)
	at feeds.FeedsFragment$importFeedsLauncher$1$1$1.invokeSuspend(FeedsFragment.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

The OPML file has the following format:

```
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<opml version="2.0">
<head>
   <title>Subscribed feeds</title>
    <dateCreated>23.04.2021 16:00:00</dateCreated>
   </head>
<body>
    <outline xmlUrl="https://example.com/feed" title="Feed title" text="Feed description" category="Feed category" />
  </body>
</opml>
```

**Comment by bubelov** [comment]
@Tiger3030 which app generated this OPML file?

http://dev.opml.org/spec2.html

> Required attributes: type, text, xmlUrl. For outline elements whose type is rss, the text attribute should initially be the top-level title element in the feed being pointed to, however since it is user-editable, processors should not depend on it always containing the title of the feed. xmlUrl is the http address of the feed. 

I didn't read this OPML spec in full, but it looks like "type" attribute is mandatory.

**Comment by bubelov** [comment]
@Tiger3030 you can simply add `type="rss"` to all of your outlines and it will pass, but it would be nice to find out what's going on here =)

**Comment by Tiger3030** [comment]
> @Tiger3030 you can simply add type="rss" to all of your outlines and it will pass, but it would be nice to find out what's going on here =)

Thanks, I have done that and it worked.

> 
> 
> @Tiger3030 which app generated this OPML file?
> 
> http://dev.opml.org/spec2.html
> 
> > Required attributes: type, text, xmlUrl. For outline elements whose type is rss, the text attribute should initially be the top-level title element in the feed being pointed to, however since it is user-editable, processors should not depend on it always containing the title of the feed. xmlUrl is the http address of the feed.
> 
> I didn't read this OPML spec in full, but it looks like "type" attribute is mandatory.

I think you are right and "type" is required. The OPML file was generated by another RSS Reader app, which is still in early access (Pluma RSS Reader), so I will inform the developers of that app about the problem.
