### ISSUE TITLE
Timeout while downloading Podcast + Feature Suggestions

### ISSUE THREAD

**Issue by Jane232** [bubelov/news#74]
When I try to download a podcast episode after this (see below) timeout error occurs.
This happens on 4 different podcast providers, my nextcloud is also up and running!
Strangely I cant even download podcast episodes that I have downloaded last week (I did a reset on the app...)

An other bug is when a episode stopped downloading due to connectivity issues, the progressbar still "continues" to download and therefore prohibits the option to try downloading again...

Feature Request / Suggestion:
- Give users the opportunity to delete downloaded episodes, after some time they really fill up the storage on my device!
- Make it compatible with the official nextcloud podcast app (sync podcasts, sync which epsisodes are new and which are old)

All in all great app :)

Error:

SocketTimeoutException
java.net.SocketTimeoutException: timeout
at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:382)
at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
at podcasts.PodcastsRepository$download$2.invokeSuspend(PodcastsRepository.kt:132)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by bubelov** [comment]
@Jane232 

Socket timeouts suggest connectivity issues, there is nothing the app can do about that, except properly handling those errors.

Cache management (podcasts and other feed items in general) is currently missing. The app is far from stable release and sometimes you need to do stuff manually. My phone has 16 GB of storage, half of which is used by system, so I totally understand your issue =) For now, you can simply nuke the `Podcasts` directory on your phone if you want to reclaim space. The app will handle missing files and it won't try to re-download them unless you tell it to do so.

Regarding official podcasts app, I never heard of that. I have to check if it can be used as a data source in any convenient way.

**Comment by bubelov** [comment]
Implemented in https://github.com/bubelov/news/commit/0620af30eefb3b830de5082fda6f7a6abf5ad8fb
