### ISSUE TITLE
Error HTTPS request fails with error code 520

### ISSUE THREAD

**Issue by citizenserious** [bubelov/news#93]
### Checklist

- [x] I am using the latest version 
- [x] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [x] This issue contains only one bug. I will open one issue for every bug report I want to file.

Steps to reproduce the bug
1. Click "Login with Nextcloud"
2. Choose an account and press ok
3. Allow News to access my nextcloud account -> press allow

### Actual behavior

Error 520 and no news fetched

### Expected behavior

Login works fine.

### Logs

java.lang.Exception: HTTPS request failed with error code 520
	at api.nextcloud.NextcloudNewsApiAdapter.toException(NextcloudNewsApiAdapter.kt:197)
	at api.nextcloud.NextcloudNewsApiAdapter.access$toException(NextcloudNewsApiAdapter.kt:15)
	at api.nextcloud.NextcloudNewsApiAdapter$getEntries$2.invokeSuspend(NextcloudNewsApiAdapter.kt:85)
	at api.nextcloud.NextcloudNewsApiAdapter$getEntries$2.invoke(Unknown Source:8)
	at api.nextcloud.NextcloudNewsApiAdapter$getEntries$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
	at entries.EntriesRepository$syncAll$2$1.invokeSuspend(EntriesRepository.kt:264)
	at entries.EntriesRepository$syncAll$2$1.invoke(Unknown Source:8)
	at entries.EntriesRepository$syncAll$2$1.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at entries.EntriesRepository$syncAll$2.invokeSuspend(EntriesRepository.kt:124)
	at entries.EntriesRepository$syncAll$2.invoke(Unknown Source:8)
	at entries.EntriesRepository$syncAll$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:212)
	at sync.NewsApiSync$performInitialSync$2$1$1$entriesSync$1.invokeSuspend(NewsApiSync.kt:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

You can add additional details if you think it might be relevant. -->

App worked fine before the update to v0.3.0.
Logged in manually before the update, which is no longer possible.
Also reinstalled the app.

### Device info

 - Android version/Custom ROM version: LOS 18.1 Android 11
 - Device model: starlte

**Comment by bubelov** [comment]
@citizenserious can't reproduce it on my own Android 11 device. Can you try installing the previous version and checking if it works? It could be NC issue but I'm not sure

**Comment by citizenserious** [comment]
With 0.2.9 I get the error that the nextcloud files app would not be installed, but when I manually login then, it works. We wrote about this error before (can't remember where), so you added the manual login option.

**Comment by bubelov** [comment]
@citizenserious I think this issue is different. It can be related to NC Android app too. I'm using 3.17.1 and it works fine, you can try downgrading and see if it helps. Also, NC released their new sign-in library yesterday and I'm going to update it in the new release, maybe it will help

**Comment by bubelov** [comment]
@citizenserious since the manual login is only available when app login fails straight away, you can't use 0.3.0, right? I think it makes sense to allow users to select manual login even if NC app is present, just to avoid this kind of situations in the future

**Comment by citizenserious** [comment]
> @citizenserious since the manual login is only available when app login fails straight away, you can't use 0.3.0, right? I think it makes sense to allow users to select manual login even if NC app is present, just to avoid this kind of situations in the future

Exactly, it does not fail anymore like in 0.2.9 so there is no question window popping up, asking me if I would like to manually login. 
That would be very nice (:

**Comment by bubelov** [comment]
@citizenserious it's added in the preview build:

https://github.com/bubelov/news/releases/tag/preview

It will also be available in F-Droid in a few days

**Comment by citizenserious** [comment]
You are awesome, thank you very much (:
